ImGuiCond = ImGuiCond or {}
ImGuiCond.None          = 0        -- No condition (always set the variable), same as _Always
ImGuiCond.Always        = (2^0)   -- No condition (always set the variable)
ImGuiCond.Once          = (2^1)   -- Set the variable once per runtime session (only the first call will succeed)
ImGuiCond.FirstUseEver  = (2^2)   -- Set the variable if the object/window has no persistently saved data (no entry in .ini file)
ImGuiCond.Appearing     = (2^3)    -- Set the variable if the object/window is appearing after being hidden/inactive (or the first time)

-- ImGuiWindowFlags = ImGuiWindowFlags or {}
-- ImGuiWindowFlags.None                   = 0
-- ImGuiWindowFlags.NoTitleBar             = (2^0)   -- Disable title-bar
-- ImGuiWindowFlags.NoResize               = (2^1)   -- Disable user resizing with the lower-right grip
-- ImGuiWindowFlags.NoMove                 = (2^2)   -- Disable user moving the window
-- ImGuiWindowFlags.NoScrollbar            = (2^3)   -- Disable scrollbars (window can still scroll with mouse or programmatically)
-- ImGuiWindowFlags.NoScrollWithMouse      = (2^4)   -- Disable user vertically scrolling with mouse wheel. On child window, mouse wheel will be forwarded to the parent unless NoScrollbar is also set.
-- ImGuiWindowFlags.NoCollapse             = (2^5)   -- Disable user collapsing window by double-clicking on it
-- ImGuiWindowFlags.AlwaysAutoResize       = (2^6)   -- Resize every window to its content every frame
-- ImGuiWindowFlags.NoBackground           = (2^7)   -- Disable drawing background color (WindowBg, etc.) and outside border. Similar as using SetNextWindowBgAlpha(0.0f).
-- ImGuiWindowFlags.NoSavedSettings        = (2^8)   -- Never load/save settings in .ini file
-- ImGuiWindowFlags.NoMouseInputs          = (2^9)   -- Disable catching mouse, hovering test with pass through.
-- ImGuiWindowFlags.MenuBar                = (2^10)  -- Has a menu-bar
-- ImGuiWindowFlags.HorizontalScrollbar    = (2^11)  -- Allow horizontal scrollbar to appear (off by default). You may use SetNextWindowContentSize(ImVec2(width,0.0f)); prior to calling Begin() to specify width. Read code in imgui_demo in the "Horizontal Scrolling" section.
-- ImGuiWindowFlags.NoFocusOnAppearing     = (2^12)  -- Disable taking focus when transitioning from hidden to visible state
-- ImGuiWindowFlags.NoBringToFrontOnFocus  = (2^13)  -- Disable bringing window to front when taking focus (e.g. clicking on it or programmatically giving it focus)
-- ImGuiWindowFlags.AlwaysVerticalScrollbar= (2^14)  -- Always show vertical scrollbar (even if ContentSize.y < Size.y)
-- ImGuiWindowFlags.AlwaysHorizontalScrollbar=(2^15)  -- Always show horizontal scrollbar (even if ContentSize.x < Size.x)
-- ImGuiWindowFlags.AlwaysUseWindowPadding = (2^16)  -- Ensure child windows without border uses style.WindowPadding (ignored by default for non-bordered child windows, because more convenient)
-- ImGuiWindowFlags.NoNavInputs            = (2^18)  -- No gamepad/keyboard navigation within the window
-- ImGuiWindowFlags.NoNavFocus             = (2^19)  -- No focusing toward this window with gamepad/keyboard navigation (e.g. skipped by CTRL+TAB)
-- ImGuiWindowFlags.UnsavedDocument        = (2^20)  -- Append '*' to title without affecting the ID, as a convenience to avoid using the ### operator. When used in a tab/docking context, tab is selected on closure and closure is deferred by one frame to allow code to cancel the closure (with a confirmation popup, etc.) without flicker.
-- ImGuiWindowFlags.NoNav                  = ImGuiWindowFlags.NoNavInputs + ImGuiWindowFlags.NoNavFocus
-- ImGuiWindowFlags.NoDecoration           = ImGuiWindowFlags.NoTitleBar + ImGuiWindowFlags.NoResize + ImGuiWindowFlags.NoScrollbar + ImGuiWindowFlags.NoCollapse
-- ImGuiWindowFlags.NoInputs               = ImGuiWindowFlags.NoMouseInputs + ImGuiWindowFlags.NoNavInputs + ImGuiWindowFlags.NoNavFocus
-- -- [Internal]
-- ImGuiWindowFlags.NavFlattened           = (2^23)  -- [BETA] Allow gamepad/keyboard navigation to cross over parent border to this child (only use on child that have no scrolling!)
-- ImGuiWindowFlags.ChildWindow            = (2^24)  -- Don't use! For internal use by BeginChild()
-- ImGuiWindowFlags.Tooltip                = (2^25)  -- Don't use! For internal use by BeginTooltip()
-- ImGuiWindowFlags.Popup                  = (2^26)  -- Don't use! For internal use by BeginPopup()
-- ImGuiWindowFlags.Modal                  = (2^27)  -- Don't use! For internal use by BeginPopupModal()
-- ImGuiWindowFlags.ChildMenu              = (2^28)   -- Don't use! For internal use by BeginMenu()

ImGuiInputTextFlags = ImGuiInputTextFlags or {}
-- ImGuiInputTextFlags.None                = 0
-- ImGuiInputTextFlags.CharsDecimal        = (2^0)   -- Allow 0123456789.+-*/
-- ImGuiInputTextFlags.CharsHexadecimal    = (2^1)   -- Allow 0123456789ABCDEFabcdef
-- ImGuiInputTextFlags.CharsUppercase      = (2^2)   -- Turn a..z into A..Z
ImGuiInputTextFlags.CharsNoBlank        = (2^3)   -- Filter out spaces, tabs
-- ImGuiInputTextFlags.AutoSelectAll       = (2^4)   -- Select entire text when first taking mouse focus
-- ImGuiInputTextFlags.EnterReturnsTrue    = (2^5)   -- Return 'true' when Enter is pressed (as opposed to every time the value was modified). Consider looking at the IsItemDeactivatedAfterEdit() function.
-- ImGuiInputTextFlags.CallbackCompletion  = (2^6)   -- Callback on pressing TAB (for completion handling)
-- ImGuiInputTextFlags.CallbackHistory     = (2^7)   -- Callback on pressing Up/Down arrows (for history handling)
-- ImGuiInputTextFlags.CallbackAlways      = (2^8)   -- Callback on each iteration. User code may query cursor position, modify text buffer.
-- ImGuiInputTextFlags.CallbackCharFilter  = (2^9)   -- Callback on character inputs to replace or discard them. Modify 'EventChar' to replace or discard, or return 1 in callback to discard.
-- ImGuiInputTextFlags.AllowTabInput       = (2^10)  -- Pressing TAB input a '\t' character into the text field
-- ImGuiInputTextFlags.CtrlEnterForNewLine = (2^11)  -- In multi-line mode, unfocus with Enter, add new line with Ctrl+Enter (default is opposite: unfocus with Ctrl+Enter, add line with Enter).
-- ImGuiInputTextFlags.NoHorizontalScroll  = (2^12)  -- Disable following the cursor horizontally
-- ImGuiInputTextFlags.AlwaysInsertMode    = (2^13)  -- Insert mode
-- ImGuiInputTextFlags.ReadOnly            = (2^14)  -- Read-only mode
-- ImGuiInputTextFlags.Password            = (2^15)  -- Password mode, display all characters as '*'
-- ImGuiInputTextFlags.NoUndoRedo          = (2^16)  -- Disable undo/redo. Note that input text owns the text data while active, if you want to provide your own undo/redo stack you need e.g. to call ClearActiveID().
-- ImGuiInputTextFlags.CharsScientific     = (2^17)  -- Allow 0123456789.+-*/eE (Scientific notation input)
-- ImGuiInputTextFlags.CallbackResize      = (2^18)  -- Callback on buffer capacity changes request (beyond 'buf_size' parameter value), allowing the string to grow. Notify when the string wants to be resized (for string types which hold a cache of their Size). You will be provided a new BufSize in the callback and NEED to honor it. (see misc/cpp/imgui_stdlib.h for an example of using this)
-- -- [Internal]
-- ImGuiInputTextFlags.Multiline           = (2^20)  -- For internal use by InputTextMultiline()
-- ImGuiInputTextFlags.NoMarkEdited        = (2^21)   -- For internal use by functions using InputText() before reformatting data

ImGuiSelectableFlags = ImGuiSelectableFlags or {}
ImGuiSelectableFlags.None               = 0
ImGuiSelectableFlags.DontClosePopups    = 1   -- Clicking this don't close parent popup window
ImGuiSelectableFlags.SpanAllColumns     = 2   -- Selectable frame can span all columns (text will still fit in current column)
ImGuiSelectableFlags.AllowDoubleClick   = 4   -- Generate press events on double clicks too
ImGuiSelectableFlags.Disabled           = 8   -- Cannot be selected, display grayed out text
ImGuiSelectableFlags.AllowItemOverlap   = 16    -- (WIP) Hit testing to allow subsequent widgets to overlap this one

ImGuiTreeNodeFlags = ImGuiTreeNodeFlags or {}
ImGuiTreeNodeFlags.None                 = 0
ImGuiTreeNodeFlags.Selected             = 1   -- Draw as selected
ImGuiTreeNodeFlags.Framed               = 2   -- Full colored frame (e.g. for CollapsingHeader)
ImGuiTreeNodeFlags.AllowItemOverlap     = 4   -- Hit testing to allow subsequent widgets to overlap this one
ImGuiTreeNodeFlags.NoTreePushOnOpen     = 8   -- Don't do a TreePush() when open (e.g. for CollapsingHeader) = no extra indent nor pushing on ID stack
ImGuiTreeNodeFlags.NoAutoOpenOnLog      = 16   -- Don't automatically and temporarily open node when Logging is active (by default logging will automatically open tree nodes)
ImGuiTreeNodeFlags.DefaultOpen          = 32   -- Default node to be open
ImGuiTreeNodeFlags.OpenOnDoubleClick    = 64   -- Need double-click to open node
ImGuiTreeNodeFlags.OpenOnArrow          = 128   -- Only open when clicking on the arrow part. If ImGuiTreeNodeFlags.OpenOnDoubleClick is also set, single-click arrow or double-click all box to open.
ImGuiTreeNodeFlags.Leaf                 = 256   -- No collapsing, no arrow (use as a convenience for leaf nodes).
ImGuiTreeNodeFlags.Bullet               = 512   -- Display a bullet instead of arrow
ImGuiTreeNodeFlags.FramePadding         = 1024  -- Use FramePadding (even for an unframed text node) to vertically align text baseline to regular widget height. Equivalent to calling AlignTextToFramePadding().
ImGuiTreeNodeFlags.SpanAvailWidth       = 2048  -- Extend hit box to the right-most edge, even if not framed. This is not the default in order to allow adding other items on the same line. In the future we may refactor the hit system to be front-to-back, allowing natural overlaps and then this can become the default.
ImGuiTreeNodeFlags.SpanFullWidth        = 4096  -- Extend hit box to the left-most and right-most edges (bypass the indented area).
ImGuiTreeNodeFlags.NavLeftJumpsBackHere = 8192  -- (WIP) Nav: left direction may move to this TreeNode() from any of its child (items submitted between TreeNode and TreePop)
ImGuiTreeNodeFlags.CollapsingHeader     = ImGuiTreeNodeFlags.Framed + ImGuiTreeNodeFlags.NoTreePushOnOpen + ImGuiTreeNodeFlags.NoAutoOpenOnLog

ImGuiKey = ImGuiKey or {}
ImGuiKey.Tab = 0
ImGuiKey.LeftArrow = 1
ImGuiKey.RightArrow = 2
ImGuiKey.UpArrow = 3
ImGuiKey.DownArrow = 4
ImGuiKey.PageUp = 5
ImGuiKey.PageDown = 6
ImGuiKey.Home = 7
ImGuiKey.End = 8
ImGuiKey.Insert = 9
ImGuiKey.Delete = 10
ImGuiKey.Backspace = 11
ImGuiKey.Space = 12
ImGuiKey.Enter = 13
ImGuiKey.Escape = 14
ImGuiKey.KeyPadEnter = 15
ImGuiKey.A = 16                 -- for text edit CTRL+A: select all
ImGuiKey.C = 17                 -- for text edit CTRL+C: copy
ImGuiKey.V = 18                 -- for text edit CTRL+V: paste
ImGuiKey.X = 19                 -- for text edit CTRL+X: cut
ImGuiKey.Y = 20                 -- for text edit CTRL+Y: redo
ImGuiKey.Z = 21                 -- for text edit CTRL+Z: undo
ImGuiKey.COUNT = 22
ImGuiKey.KEY_0 = 48
ImGuiKey.KEY_1 = 49
ImGuiKey.KEY_2 = 50
ImGuiKey.KEY_3 = 51
ImGuiKey.KEY_4 = 52
ImGuiKey.KEY_5 = 53
ImGuiKey.KEY_6 = 54
ImGuiKey.KEY_7 = 55
ImGuiKey.KEY_8 = 56
ImGuiKey.KEY_9 = 57