entvars_s = {
    classname           = 1,        -- string_t
    globalname          = 2,        -- string_t
    origin              = 3,        -- vec3_t
    velocity            = 4,        -- vec3_t
    basevelocity        = 5,        -- vec3_t
    clbasevelocity      = 6,        -- vec3_t
    movedir             = 7,        -- vec3_t
    angles              = 8,        -- vec3_t
    avelocity           = 9,        -- vec3_t
    punchangle          = 10,       -- vec3_t
    v_angle             = 11,       -- vec3_t
    endpos              = 12,       -- vec3_t
    startpos            = 13,       -- vec3_t
    impacttime          = 14,       -- time_point_t
    starttime           = 15,       -- time_point_t
    fixangle            = 16,       -- int
    idealpitch          = 17,       -- float
    pitch_spee          = 18,       -- float
    ideal_yaw           = 19,       -- float
    yaw_speed           = 20,       -- float
    modelindex          = 21,       -- int
    model               = 22,       -- string_t
    viewmodel           = 23,       -- int
    weaponmode          = 24,       -- int
    absmin              = 25,       -- vec3_t
    absmax              = 26,       -- vec3_t
    mins                = 27,       -- vec3_t
    maxs                = 28,       -- vec3_t
    size                = 29,       -- vec3_t
    ltime               = 30,       -- time_point_t
    nextthink           = 31,       -- time_point_t
    movetype            = 32,       -- int
    solid               = 33,       -- int
    skin                = 34,       -- int
    body                = 35,       -- int
    effects             = 36,       -- int
    gravity             = 37,       -- float
    friction            = 38,       -- float
    light_leve          = 39,       -- int
    sequence            = 40,       -- int
    gaitsequen          = 41,       -- int
    frame               = 42,       -- float
    animtime            = 43,       -- time_point_t
    framerate           = 44,       -- float
    controller          = 45,       -- byte[4]
    blending            = 46,       -- byte[2]
    scale               = 47,       -- float
    rendermode          = 48,       -- int
    renderamt           = 49,       -- float
    rendercolo          = 50,       -- vec3_t
    renderfx            = 51,       -- int
    health              = 52,       -- float
    frags               = 53,       -- float
    weapons             = 54,       -- int
    takedamage          = 55,       -- float
    deadflag            = 56,       -- int
    view_ofs            = 57,       -- vec3_t
    button              = 58,       -- int
    impulse             = 59,       -- int
    chain               = 60,       -- edict_t *
    dmg_inflic          = 61,       -- edict_t *
    enemy               = 62,       -- edict_t *
    aiment              = 63,       -- edict_t *
    owner               = 64,       -- edict_t *
    groundenti          = 65,       -- edict_t *
    spawnflags          = 66,       -- int
    flags               = 67,       -- int
    colormap            = 68,       -- int
    team                = 69,       -- int
    max_health          = 70,       -- float
    teleport_t          = 71,       -- float
    armortype           = 72,       -- float
    armorvalue          = 73,       -- float
    waterlevel          = 74,       -- int
    watertype           = 75,       -- int
    target              = 76,       -- string_t
    targetname          = 77,       -- string_t
    netname             = 78,       -- string_t
    message             = 79,       -- string_t
    dmg_take            = 80,       -- float
    dmg_save            = 81,       -- float
    dmg                 = 82,       -- float
    dmgtime             = 83,       -- time_point_t
    noise               = 84,       -- string_t
    noise1              = 85,       -- string_t
    noise2              = 86,       -- string_t
    noise3              = 87,       -- string_t
    speed               = 88,       -- float
    air_finish          = 89,       -- time_point_t
    pain_finis          = 90,       -- time_point_t
    radsuit_fi          = 91,       -- time_point_t
    pContainin          = 92,       -- edict_t *
    playerclas          = 93,       -- int
    maxspeed            = 94,       -- float
    fov                 = 95,       -- float
    weaponanim          = 96,       -- int
    pushmsec            = 97,       -- int
    bInDuck             = 98,       -- int
    flTimeStep          = 99,       -- int
    flSwimTime          = 100,      -- int
    flDuckTime          = 101,      -- int
    iStepLeft           = 102,      -- int
    flFallVelo          = 103,      -- float
    gamestate           = 104,      -- int
    oldbuttons          = 105,      -- int
    groupinfo           = 106,      -- int
    iuser1              = 107,      -- int
    iuser2              = 108,      -- int
    iuser3              = 109,      -- int
    iuser4              = 110,      -- int
    fuser1              = 111,      -- float
    fuser2              = 112,      -- float
    fuser3              = 113,      -- float
    fuser4              = 114,      -- float
    vuser1              = 115,      -- vec3_t
    vuser2              = 116,      -- vec3_t
    vuser3              = 117,      -- vec3_t
    vuser4              = 118,      -- vec3_t
    euser1              = 119,      -- edict_t *
    euser2              = 120,      -- edict_t *
    euser3              = 121,      -- edict_t *
    euser4              = 122,      -- edict_t *
}
entvars_t = entvars_s
return entvars_s