model_s = {
    name = 1,
	needload = 2, -- qboolean bmodels and sprites don't cache normally
	type = 3, -- modtype_t
	numframes = 4, -- int
	mempool = 5, -- byte*;		-- private mempool (was synctype)
	flags = 6, -- int
	mins = 7, -- vec3_t
	maxs = 8, -- vec3_t
	radius = 9, -- float
	firstmodelsurface = 10, -- int
	nummodelsurfaces = 11, -- int
	numsubmodels = 12, -- int
	submodels = 13, -- dmodel_t	*
	numplanes = 14, -- int
	planes = 15, -- mplane_t	*
	numleafs = 16, -- int   number of visible leafs, not counting 0
	leafs = 17, -- struct mleaf_s *
	numvertexes = 18, -- int
	vertexes = 19, -- mvertex_t	*
	numedges = 20, -- int
	edges = 21, -- medge_t		*
	numnodes = 22, -- int
	nodes = 23, -- mnode_t		*
	numtexinfo = 24, -- int
	texinfo = 25, -- mtexinfo_t	*
	numsurfaces = 26, -- int
	surfaces = 27, -- msurface_t	*
	numsurfedges = 28, -- int
	surfedges = 29, -- int
	numclipnodes = 30, -- int
	clipnodes = 31, -- dclipnode_t	*
	nummarksurfaces = 32, -- int
	marksurfaces = 33, -- msurface_t	**
	hulls = 34,-- hull_t [MAX_MAP_HULLS]
	numtextures = 35, -- int
	textures = 36, -- texture_t	**
	visdata = 37, -- byte		*
	lightdata = 38, -- color24		*
	entities = 39, -- char		*
	cache = 40 -- cache_user_t	only access through Mod_Extradata
}
model_t = model_s
return model_s