
CHAN_AUTO = 0
CHAN_WEAPON = 1
CHAN_VOICE = 2
CHAN_ITEM = 3
CHAN_BODY = 4
CHAN_STREAM = 5	-- allocate stream channel from the static or dynamic area
CHAN_STATIC = 6	-- allocate channel from the static area 
CHAN_NETWORKVOICE_BASE = 7	-- voice data coming across the network
CHAN_NETWORKVOICE_END = 500	-- network voice data reserves slots (CHAN_NETWORKVOICE_BASE through CHAN_NETWORKVOICE_END).
CHAN_BOT = 501 -- channel used for bot chatter

ATTN_NONE = 0
ATTN_NORM = 0.8
ATTN_IDLE = 2
ATTN_STATIC = 1.25 

PITCH_NORM = 100 -- non-pitch shifted
PITCH_LOW = 95 -- other values are possible - 0-255, where 255 is very high
PITCH_HIGH = 120

TE_BOUNCE_NULL = 0
TE_BOUNCE_SHELL = 1
TE_BOUNCE_SHOTSHELL = 2

BULLET_NONE = 0
BULLET_PLAYER_9MM = 1
BULLET_PLAYER_MP5 = 2
BULLET_PLAYER_357 = 3
BULLET_PLAYER_BUCKSHOT = 4
BULLET_PLAYER_CROWBAR = 5
BULLET_MONSTER_9MM = 6
BULLET_MONSTER_MP5 = 7
BULLET_MONSTER_12MM = 8
BULLET_PLAYER_45ACP = 9
BULLET_PLAYER_338MAG = 10
BULLET_PLAYER_762MM = 11
BULLET_PLAYER_556MM = 12
BULLET_PLAYER_50AE = 13
BULLET_PLAYER_57MM = 14
BULLET_PLAYER_357SIG = 15

return {}